spring:
    datasource:
        url: jdbc:mysql://192.168.1.106:3306/shiro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: Sxj19961226.
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    redis:
    # Redis数据库索引（默认为0）
      database: 0  
    # Redis服务器地址
      host: 192.168.1.101
    # Redis服务器连接端口
      port: 6379  
    # Redis服务器连接密码（默认为空）
      password: 130119
    # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 8  
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: 5000 
    # 连接池中的最大空闲连接
      pool.max-idle: 8  
    # 连接池中的最小空闲连接
      pool.min-idle: 0  
    # 连接超时时间（毫秒）
      timeout: 0